%option outfile="program1_lex.cpp"
%option noyywrap

operand		"=="|">="|"<="|"!="|"<"|">"
comparator	"||"|"&&"
math_op		[+*/-]
enclosing_op	[\[\{()\}\]]
punctuation	[.,;]
identifier	[_a-zA-Z][_0-9a-zA-Z]*
number		[0-9]+
exponent	[eE][+-]?{number}
decimal		["."]{number}{exponent}?
float		{number}[{exponent}{decimal}]
tab		[\t]
space		[ ]+


%%

{operand}		return 1;
{comparator}		return 2;
{math_op}		return 3;
{enclosing_op}		return 4;
{punctuation}		return 5;
this|if|else|while	return 6;
{identifier}		return 7;
{number}		return 8;
{number}{decimal}	return 9;
{number}{exponent}	return 9;
"\n"			return 11;
{space}			return 12;
{tab}			return 13;
"/*"			return 14;
"*/"			return 15;
.			return 10;
